<?php

/*
|--------------------------------------------------------------------------
| Sequence-generation probe (READ ONLY)
|--------------------------------------------------------------------------
| No application code was changed — this file only observes how the codes
| are generated by App\Traits\GeneratesCodes and whether the counter
| restarts when the year (and month) changes.
|
| Generators under test:
|   PasController::create()            -> "PAS-{YYYY}-{MM}-{NNNN}"
|   ReleaseController::create()        -> "{TYPE}-{YYYY}-{MM}-{NNNN}"
|   ReleaseController::nextPtrNumber() -> same, used by the type switcher
|   ReceivingController::create()      -> "{PREFIX}-{YY}-{MM}-{NNNN}" seed
|     (the receiving form's JS appends the 4-digit sequence to that seed)
*/

use App\Http\Controllers\PasController;
use App\Http\Controllers\ReceivingController;
use App\Http\Controllers\ReleaseController;
use App\Models\Item;
use App\Models\Pas;
use App\Models\PasItem;
use App\Models\Program;
use App\Models\Receiving;
use App\Models\ReceivingItem;
use App\Models\Release;
use App\Models\Supplier;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

uses(RefreshDatabase::class);

function probeSeedPasNumber(string $pasNumber): void
{
    Pas::create([
        'pas_number'           => $pasNumber,
        'date_of_pass'         => Carbon::now()->toDateString(),
        'facility_name'        => 'Probe Facility',
        'facility_coordinator' => 'Probe Coordinator',
        'transfer_type'        => 'PTR',
        'status'               => 'Pending',
    ]);
}

function probeSeedRelease(string $releaseNumber, string $ptrItrRisNo): void
{
    Release::create([
        'release_number' => $releaseNumber,
        'ptr_itr_ris_no' => $ptrItrRisNo,
        'date_released'  => Carbon::now()->toDateString(),
        'status'         => 'Pending',
    ]);
}

function probeSeedReceivingItemCode(string $itemCode): void
{
    $supplier = Supplier::firstOrCreate(['company_name' => 'Probe Supplier']);

    $receiving = Receiving::create([
        'supplier_id'   => $supplier->id,
        'date_received' => Carbon::now()->toDateString(),
    ]);

    $item = Item::create(['name' => 'Probe Item ' . $itemCode]);

    ReceivingItem::create([
        'receiving_id'      => $receiving->id,
        'item_id'           => $item->id,
        'item_code'         => $itemCode,
        'item_description'  => 'Probe row for ' . $itemCode,
        'quantity_received' => 1,
    ]);
}

/** The PAS number the "New PAS" form pre-fills. */
function probePasNumber(): string
{
    return app(PasController::class)->create()->getData()['pasNumber'];
}

/** The PTR/ITR/RIS number the release form (or its type switcher) suggests. */
function probePtrNumber(string $type = 'PTR'): string
{
    if ($type === 'PTR') {
        return app(ReleaseController::class)->create()->getData()['ptrNumber'];
    }

    $response = app(ReleaseController::class)->nextPtrNumber($type);

    return json_decode($response->getContent(), true)['number'];
}

/** The next 4-digit sequence the receiving form seeds per program prefix. */
function probeItemCodeSequence(string $prefix): int
{
    $data = app(ReceivingController::class)->create()->getData();

    return (int) ($data['programSequences'][$prefix] ?? 0);
}


test('PAS number sequence restarts every month and therefore at every new year', function () {
    // Rows from other months / years must never leak into the current counter.
    probeSeedPasNumber('PAS-2025-12-0050'); // previous year
    probeSeedPasNumber('PAS-2026-08-0100'); // previous month, same year
    probeSeedPasNumber('PAS-2026-09-0001');
    probeSeedPasNumber('PAS-2026-09-0002');

    $this->travelTo(Carbon::parse('2026-09-15 10:00:00'));
    expect(probePasNumber())->toBe('PAS-2026-09-0003'); // continues inside the same month

    $this->travelTo(Carbon::parse('2026-10-01 10:00:00'));
    expect(probePasNumber())->toBe('PAS-2026-10-0001'); // month reset (still year 2026)

    $this->travelTo(Carbon::parse('2027-01-04 10:00:00'));
    expect(probePasNumber())->toBe('PAS-2027-01-0001'); // year reset
});

test('PTR / ITR / RIS number sequence restarts every month and therefore at every new year', function () {
    probeSeedRelease('REL-PROBE-1', 'PTR-2025-12-0099'); // previous year
    probeSeedRelease('REL-PROBE-2', 'PTR-2026-11-0100'); // previous month, same year
    probeSeedRelease('REL-PROBE-3', 'PTR-2026-12-0001');
    probeSeedRelease('REL-PROBE-4', 'ITR-2026-12-0002');
    probeSeedRelease('REL-PROBE-5', 'RIS-2026-12-0003');

    $this->travelTo(Carbon::parse('2026-12-20 09:00:00'));

    // PTR, ITR and RIS share ONE counter for the same year-month.
    expect(probePtrNumber())->toBe('PTR-2026-12-0004');
    expect(probePtrNumber('ITR'))->toBe('ITR-2026-12-0004');
    expect(probePtrNumber('RIS'))->toBe('RIS-2026-12-0004');

    $this->travelTo(Carbon::parse('2027-01-02 09:00:00'));
    expect(probePtrNumber())->toBe('PTR-2027-01-0001'); // year reset
    expect(probePtrNumber('ITR'))->toBe('ITR-2027-01-0001');

    $this->travelTo(Carbon::parse('2027-02-01 09:00:00'));
    expect(probePtrNumber())->toBe('PTR-2027-02-0001'); // month reset (still year 2027)
});

test('receiving item code seed restarts every month and therefore at every new year', function () {
    Program::create(['name' => 'DOH Program', 'description' => 'DOH']);

    probeSeedReceivingItemCode('DOH-25-12-0100'); // previous year
    probeSeedReceivingItemCode('DOH-26-08-0100'); // previous month, same year
    probeSeedReceivingItemCode('DOH-26-09-0001');
    probeSeedReceivingItemCode('DOH-26-09-0002');

    $this->travelTo(Carbon::parse('2026-09-15 08:00:00'));
    expect(probeItemCodeSequence('DOH'))->toBe(3);

    $this->travelTo(Carbon::parse('2026-10-01 08:00:00'));
    expect(probeItemCodeSequence('DOH'))->toBe(1);

    $this->travelTo(Carbon::parse('2027-01-04 08:00:00'));
    expect(probeItemCodeSequence('DOH'))->toBe(1);
});

test('the full item code the receiving form assembles is PREFIX-YY-MM-NNNN and restarts at the new year', function () {
    Program::create(['name' => 'DOH Program', 'description' => 'DOH']);
    probeSeedReceivingItemCode('DOH-26-09-0001');

    $this->travelTo(Carbon::parse('2026-09-15 08:00:00'));
    $seq = probeItemCodeSequence('DOH');
    expect(sprintf('DOH-%s-%s-%04d', now()->format('y'), now()->format('m'), $seq))
        ->toBe('DOH-26-09-0002');

    $this->travelTo(Carbon::parse('2027-01-04 08:00:00'));
    $seq = probeItemCodeSequence('DOH');
    expect(sprintf('DOH-%s-%s-%04d', now()->format('y'), now()->format('m'), $seq))
        ->toBe('DOH-27-01-0001');
});

/*
 * KNOWN ISSUE found by this probe (nothing was changed):
 * pas_items.product_code is built as 'PC' + YY + MM + NNNN with NO separator,
 * while GeneratesCodes::nextYearSequence() reads the running number with the
 * greedy regex /(\d+)$/. That regex also swallows the YYMM digits, so every
 * new code is stacked on top of the previous one and keeps growing:
 *   PC26090001 -> PC260926090002 -> PC2609260926090003 -> ...
 * The same corruption is already present in the live database.
 * PAS / PTR / receiving item codes are unaffected because their groups are
 * separated by dashes, so /(\d+)$/ only captures the 4-digit sequence.
 */
test('PAS item product code (PHO code) does not restart cleanly - digits pile up (known issue)', function () {
    $admin = User::factory()->create(); // no program_id => PAS number is typed in manually

    $storePas = function (string $pasNumber, string $date) use ($admin) {
        $request = Request::create('/pas', 'POST', [
            'pas_number'           => $pasNumber,
            'date_of_pass'         => $date,
            'transfer_type'        => 'PTR',
            'facility_name'        => 'Probe Facility',
            'facility_coordinator' => 'Probe Coordinator',
            'items'                => [[
                'item_description' => 'Probe PAS item ' . $pasNumber,
                'quantity'         => 2,
                'unit'             => 'kits',
                'unit_cost'        => 10,
            ]],
        ]);
        $request->setUserResolver(fn () => $admin);

        app(PasController::class)->store($request);

        return PasItem::where('item_description', 'Probe PAS item ' . $pasNumber)
            ->value('product_code');
    };

    $this->travelTo(Carbon::parse('2026-09-05 09:00:00'));
    expect($storePas('PAS-2026-09-0001', '2026-09-05'))->toBe('PC26090001'); // first of the month is fine

    $this->travelTo(Carbon::parse('2026-09-06 09:00:00'));
    expect($storePas('PAS-2026-09-0002', '2026-09-06'))->toBe('PC260926090002'); // YYMM absorbed again

    $this->travelTo(Carbon::parse('2026-09-07 09:00:00'));
    expect($storePas('PAS-2026-09-0003', '2026-09-07'))->toBe('PC2609260926090003'); // keeps growing

    // The month/year prefix is still honoured, so a new year does start clean.
    $this->travelTo(Carbon::parse('2027-01-05 09:00:00'));
    expect($storePas('PAS-2027-01-0001', '2027-01-05'))->toBe('PC27010001');
});

